// Generated by CoffeeScript 1.9.1
var fs, path;

fs = require('fs');

if (process.argv.length === 3) {
  path = process.argv[2];
  fs.readFile(path, {
    encoding: "utf-8",
    flag: "r"
  }, function(err, data) {
    var obj, re, result;
    if (err) {
      console.log(err);
    }
    re = /fileInfo\s+("|')(shot_piece_[\d]+)\1\s+("|')({.*?})\3\s*;/g;
    obj = {};
    while ((result = re.exec(data)) != null) {
      obj[result[2]] = JSON.parse(decodeURI(result[4]).replace(/\\("|')/g, "$1"));
    }
    return console.log(obj);
  });
} else {
  console.log("Please provide a file to parse. :)");
}
